import './globals.scss'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <Link href="/" style={{
            margin: '10px',
            border: '2px solid black',
          }}>Home</Link>
        </div>
        <div>{children}</div>
      </body>
    </html>
  )
}
